/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Clases.manejador_bd;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Yanir
 */
public class EditServ extends javax.swing.JFrame {

    
    private ResultSet rs = null;
    private static manejador_bd BD;
    
   
    
    public EditServ() throws SQLException {
        
        initComponents();
        this.setTitle("Servicios.");
        this.getContentPane().remove(Aceptarbtn);
        this.getContentPane().remove(Serviciotextfield);
        BD = new manejador_bd();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Servicioslist = new java.awt.List();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Editarbtn = new javax.swing.JButton();
        Nombrelbl = new javax.swing.JLabel();
        Serviciotextfield = new javax.swing.JTextField();
        Aceptarbtn = new javax.swing.JButton();
        Productoslist = new java.awt.List();
        CamionesList = new java.awt.List();
        ProveedoresList = new java.awt.List();
        EliminarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Servicioslist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicioslistActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Productos");

        jLabel3.setText("Camiones");

        jLabel4.setText("Proveedores");

        Editarbtn.setText("Editar");
        Editarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarbtnActionPerformed(evt);
            }
        });

        Nombrelbl.setText(" ");

        Aceptarbtn.setText("Aceptar");
        Aceptarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarbtnActionPerformed(evt);
            }
        });

        Productoslist.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Productoslist.setName(""); // NOI18N

        CamionesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamionesListActionPerformed(evt);
            }
        });

        EliminarBtn.setText("Eliminar");
        EliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Servicioslist, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Serviciotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Aceptarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EliminarBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ProveedoresList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Nombrelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(Editarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Productoslist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CamionesList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Editarbtn)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Nombrelbl)
                                        .addComponent(jLabel1))))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(Productoslist, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(CamionesList, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(ProveedoresList, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(EliminarBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Serviciotextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Aceptarbtn)))
                        .addComponent(Servicioslist, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ServicioslistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicioslistActionPerformed

        //Servicioslist.removeAll();
        String seleccion;
        seleccion = Servicioslist.getSelectedItem();
        Nombrelbl.setText(seleccion);
        
        try {
            rs = BD.st.executeQuery("select Automovil_Model, Automovil_Placa, Razon_Social, Inventario_Marca, Inventario_Producto " +
                                "from (select idTipo_Servicio from tipo_servicio where Descripcion = '"+seleccion+"') as ts " +
                                "right join tipo_servicio_has_automovil  " +
                                "on ts.idTipo_Servicio = tipo_servicio_has_automovil.Tipo_Servicio_idTipo_Servicio  " +
                                "right join tipo_servicio_has_proveedor " +
                                "on ts.idTipo_Servicio = tipo_servicio_has_proveedor.Tipo_Servicio_idTipo_Servicio " +
                                "right join inventario_has_tipo_servicio " +
                                "on ts.idTipo_Servicio = inventario_has_tipo_servicio.Tipo_Servicio_idTipo_Servicio;");
            rs.beforeFirst();
            
            while (rs.next()){
                Productoslist.add(rs.getString("Inventario_Producto") + " - " + rs.getString("Inventario_Marca"));
                CamionesList.add(rs.getString("Automovil_Model") + " - " + rs.getString("Automovil_Placa"));
                ProveedoresList.add(rs.getString("Razon_Social"));
            }
            repaint();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }

       
    }//GEN-LAST:event_ServicioslistActionPerformed

    private void EditarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarbtnActionPerformed
        
        this.getContentPane().remove(Editarbtn);
        this.getContentPane().remove(Nombrelbl);
        Serviciotextfield.setText(this.Nombrelbl.getText());
        Serviciotextfield.setBounds(this.Nombrelbl.getBounds());
        Aceptarbtn.setBounds(this.Editarbtn.getBounds());
      
        this.add(Aceptarbtn);
        this.add(Serviciotextfield);
        repaint();
        
    }//GEN-LAST:event_EditarbtnActionPerformed

    private void AceptarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarbtnActionPerformed
        
        try {
            BD.st.execute("UPDATE tipo_servicio SET  Descripcion = '"+Serviciotextfield.getText()+"' WHERE Descripcion = '"+Nombrelbl.getText()+"' ;");
            rellenar();
            Nombrelbl.setText(Serviciotextfield.getText());
            this.getContentPane().remove(Aceptarbtn);
            this.getContentPane().remove(Serviciotextfield);
            this.add(Nombrelbl);
            this.add(Editarbtn);
            repaint();
        } catch (SQLException ex) {
            Logger.getLogger(EditServ.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_AceptarbtnActionPerformed

    private void CamionesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamionesListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamionesListActionPerformed

    private void EliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBtnActionPerformed
        try {
            BD.st.execute("DELETE FROM `servi_cam`.`tipo_servicio` WHERE `Descripcion`='"+Nombrelbl.getText()+"';");
            rellenar ();
        } catch (SQLException ex) {
            Logger.getLogger(EditServ.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EliminarBtnActionPerformed

    private void rellenar () throws SQLException{
            
            Servicioslist.removeAll();
            Productoslist.removeAll();
           rs = BD.st.executeQuery("SELECT Descripcion FROM servi_cam.tipo_servicio;");
            int i;
            
            for(i=0; rs.next(); i++);
            
            rs.beforeFirst();
            String servicios []= new String [i];  
            
            for(i=0; rs.next(); i++)
            {
                
             System.out.println( servicios [i] = rs.getString("Descripcion"));
            }
            
            
  
            for (i = 0; i<=servicios.length-1;i++){
                Servicioslist.add(servicios[i]);
            }
        
            
            
            
            
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());  
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptarbtn;
    private java.awt.List CamionesList;
    private javax.swing.JButton Editarbtn;
    private javax.swing.JButton EliminarBtn;
    private javax.swing.JLabel Nombrelbl;
    private java.awt.List Productoslist;
    private java.awt.List ProveedoresList;
    private java.awt.List Servicioslist;
    private javax.swing.JTextField Serviciotextfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
