/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Clases.manejador_bd;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yanir
 */
public class formulario_producto extends javax.swing.JFrame {

    private Inventario inventario;
    private manejador_bd BD;
    /**
     * Creates new form formulario_producto
     * @param inv
     * @throws java.sql.SQLException
     */
    public formulario_producto(Inventario inv) throws SQLException {
        initComponents();
        this.setTitle("Producto.");
        inventario = inv;
        BD = new manejador_bd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Productolbl = new javax.swing.JLabel();
        Marcalbl = new javax.swing.JLabel();
        Mostrarbtn = new javax.swing.JButton();
        Productotxf = new javax.swing.JTextField();
        Marcatxf = new javax.swing.JTextField();
        SalirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Productolbl.setText("Producto");

        Marcalbl.setText("Marca");

        Mostrarbtn.setText("Mostrar");
        Mostrarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarbtnActionPerformed(evt);
            }
        });

        Productotxf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductotxfActionPerformed(evt);
            }
        });

        SalirBtn.setText("Salir");
        SalirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Productolbl)
                    .addComponent(Marcalbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Mostrarbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(SalirBtn))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Productotxf)
                        .addComponent(Marcatxf, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Productolbl)
                    .addComponent(Productotxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marcalbl)
                    .addComponent(Marcatxf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mostrarbtn)
                    .addComponent(SalirBtn))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MostrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarbtnActionPerformed
       
        ResultSet rs = null ;
        inventario.setProducto(Productotxf.getText());
        inventario.setMarca(Marcatxf.getText());
        try {
            rs = BD.st.executeQuery("select count(*) as cantidad from inventario where Producto = '"+Productotxf.getText()+"' and Marca = '"+Marcatxf.getText()+"'  ; ");
            rs.beforeFirst();
            rs.next();
            
            if (rs.getInt("cantidad")> 0){
                switch (inventario.tipo_historial){
                    case 1:
                        try {
                            inventario.historial();
                            inventario.setVisible(true);
                            dispose();
                        } catch (SQLException ex) {
                            Logger.getLogger(formulario_producto.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;

                    case 2:

                        try {
                            inventario.historial_movimientos();
                            inventario.setVisible(true);
                            dispose();
                        } catch (SQLException ex) {
                            Logger.getLogger(formulario_producto.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        break;
                }
            }else{
                JOptionPane.showMessageDialog(null,"El producto introducido no existe.","Informacion", JOptionPane.WARNING_MESSAGE);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(formulario_producto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_MostrarbtnActionPerformed

    private void ProductotxfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductotxfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductotxfActionPerformed

    private void SalirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBtnActionPerformed
        dispose();
    }//GEN-LAST:event_SalirBtnActionPerformed

       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Marcalbl;
    private javax.swing.JTextField Marcatxf;
    private javax.swing.JButton Mostrarbtn;
    private javax.swing.JLabel Productolbl;
    private javax.swing.JTextField Productotxf;
    private javax.swing.JButton SalirBtn;
    // End of variables declaration//GEN-END:variables
}
