/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Grafica;

import Objetos.CrearImagen;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Yanir
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.setTitle("Servicam.");
        this.setLocationRelativeTo(null);
        CrearImagen panel = new CrearImagen(PanelC, "/Imagenes/Camion.jpg");
        PanelC.add(panel);
        CrearImagen panel1 = new CrearImagen(PanelS, "/Imagenes/Servicio4.jpg");
        PanelS.add(panel1);
        CrearImagen panel2 = new CrearImagen(PanelP, "/Imagenes/proveedor.jpg");
        PanelP.add(panel2);
       CrearImagen panel3 = new CrearImagen(PanelC, "/Imagenes/Inventario.jpg");
        PanelI.add(panel3);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelC = new javax.swing.JPanel();
        ConsultaC = new javax.swing.JButton();
        CrEdC = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PanelS = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CrTS = new javax.swing.JButton();
        EditarS = new javax.swing.JButton();
        PanelI = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ConsultarI = new javax.swing.JButton();
        CrEdI = new javax.swing.JButton();
        ServiBtn = new javax.swing.JButton();
        PanelP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CrEdP = new javax.swing.JButton();
        ConsultarP = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono2.png")).getImage());
        setPreferredSize(new java.awt.Dimension(886, 230));
        setResizable(false);

        PanelC.setPreferredSize(new java.awt.Dimension(220, 190));

        ConsultaC.setText("Consultar");
        ConsultaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaCActionPerformed(evt);
            }
        });

        CrEdC.setText("Crear / Editar");
        CrEdC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrEdCActionPerformed(evt);
            }
        });

        jLabel1.setText("Camiones.");

        javax.swing.GroupLayout PanelCLayout = new javax.swing.GroupLayout(PanelC);
        PanelC.setLayout(PanelCLayout);
        PanelCLayout.setHorizontalGroup(
            PanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConsultaC, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrEdC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelCLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel1)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        PanelCLayout.setVerticalGroup(
            PanelCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(ConsultaC)
                .addGap(29, 29, 29)
                .addComponent(CrEdC)
                .addGap(60, 60, 60))
        );

        PanelS.setPreferredSize(new java.awt.Dimension(220, 190));

        jLabel2.setText("Servicios.");

        CrTS.setText("Nuevo tipo de servicio");
        CrTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrTSActionPerformed(evt);
            }
        });

        EditarS.setText("Editar servicio");
        EditarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSLayout = new javax.swing.GroupLayout(PanelS);
        PanelS.setLayout(PanelSLayout);
        PanelSLayout.setHorizontalGroup(
            PanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
            .addGroup(PanelSLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrTS)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSLayout.createSequentialGroup()
                        .addComponent(EditarS)
                        .addGap(18, 18, 18)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelSLayout.setVerticalGroup(
            PanelSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(CrTS)
                .addGap(31, 31, 31)
                .addComponent(EditarS)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelI.setPreferredSize(new java.awt.Dimension(220, 190));

        jLabel4.setText("Inventario.");

        ConsultarI.setText("Consultar");
        ConsultarI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarIActionPerformed(evt);
            }
        });

        CrEdI.setText("Crear / Editar");
        CrEdI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrEdIActionPerformed(evt);
            }
        });

        ServiBtn.setText("Servicios");
        ServiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelILayout = new javax.swing.GroupLayout(PanelI);
        PanelI.setLayout(PanelILayout);
        PanelILayout.setHorizontalGroup(
            PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelILayout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelILayout.createSequentialGroup()
                        .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelILayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4))
                            .addGroup(PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CrEdI)
                                .addComponent(ConsultarI, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelILayout.createSequentialGroup()
                        .addComponent(ServiBtn)
                        .addGap(66, 66, 66))))
        );
        PanelILayout.setVerticalGroup(
            PanelILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelILayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(ConsultarI)
                .addGap(30, 30, 30)
                .addComponent(CrEdI)
                .addGap(18, 18, 18)
                .addComponent(ServiBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelP.setPreferredSize(new java.awt.Dimension(220, 190));

        jLabel3.setText("Proveedores");

        CrEdP.setText("Crear / Editar");
        CrEdP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrEdPActionPerformed(evt);
            }
        });

        ConsultarP.setText("Consultar");
        ConsultarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelPLayout = new javax.swing.GroupLayout(PanelP);
        PanelP.setLayout(PanelPLayout);
        PanelPLayout.setHorizontalGroup(
            PanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPLayout.createSequentialGroup()
                .addGroup(PanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3))
                    .addGroup(PanelPLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(PanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrEdP)
                            .addComponent(ConsultarP, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 66, Short.MAX_VALUE))
        );
        PanelPLayout.setVerticalGroup(
            PanelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addComponent(ConsultarP)
                .addGap(30, 30, 30)
                .addComponent(CrEdP)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
            .addComponent(PanelP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
            .addComponent(PanelI, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
            .addComponent(PanelS, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ConsultaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCActionPerformed
        Cam camiones;
        try {
            camiones = new Cam ();
            camiones.setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultaCActionPerformed

    private void CrEdCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrEdCActionPerformed
        NuevoCam nuevo;
        try {
            nuevo = new NuevoCam ();
            nuevo.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CrEdCActionPerformed

    private void ConsultarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPActionPerformed
        try {
            Proveedores provedor = new Proveedores();
            provedor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarPActionPerformed

    private void CrEdPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrEdPActionPerformed
            NuevoProveedor proveedor;
        try {
            proveedor = new NuevoProveedor ();
            proveedor.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_CrEdPActionPerformed

    private void ConsultarIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarIActionPerformed
        Inventario inv;
        try {
            inv = new Inventario ();
            inv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ConsultarIActionPerformed

    private void CrEdIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrEdIActionPerformed
        NuevoProducto inv;
        try {
            inv = new NuevoProducto();
            inv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CrEdIActionPerformed

    private void CrTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrTSActionPerformed
        NuevoTS ts;
        try {
            ts = new NuevoTS();
            ts.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_CrTSActionPerformed

    private void EditarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarSActionPerformed
        EditServ es ;
        try {
            es = new EditServ ();
            es.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_EditarSActionPerformed

    private void ServiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiBtnActionPerformed
        try {
            Tabla_Serv serv = new Tabla_Serv();
            serv.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ServiBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 try {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());  
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
                new Index().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsultaC;
    private javax.swing.JButton ConsultarI;
    private javax.swing.JButton ConsultarP;
    private javax.swing.JButton CrEdC;
    private javax.swing.JButton CrEdI;
    private javax.swing.JButton CrEdP;
    private javax.swing.JButton CrTS;
    private javax.swing.JButton EditarS;
    private javax.swing.JPanel PanelC;
    private javax.swing.JPanel PanelI;
    private javax.swing.JPanel PanelP;
    private javax.swing.JPanel PanelS;
    private javax.swing.JButton ServiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

 
  
}
