/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Grafica;

import Objetos.manejador_bd;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Yanir
 */
public class NuevoTS extends javax.swing.JFrame {

    /**
     * Creates new form NuevoTS
     */
    
    private static manejador_bd BD;
   
    
    
    
    public NuevoTS() throws SQLException {
        initComponents();
        this.setTitle("Crear un nuevo tipo de servicio.");
        BD = new manejador_bd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ServicioTEXT = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        Eliminarbtn = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Servicio");

        ServicioTEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServicioTEXTActionPerformed(evt);
            }
        });

        button1.setLabel("Agregar");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        Eliminarbtn.setLabel("Eliminar");
        Eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(ServicioTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(Eliminarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ServicioTEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ServicioTEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicioTEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServicioTEXTActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        ResultSet rs = null;
        boolean flag = true;
        
        try {
            rs = BD.st.executeQuery("SELECT distinct  Descripcion from tipo_servicio;");
            rs.beforeFirst();
        } catch (SQLException ex) {
            Logger.getLogger(NuevoTS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            while(rs.next()){
                if (!ServicioTEXT.equals(rs.getString("Discripcion")))
                    flag = false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoTS.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(flag){
            try {
                BD.st.execute( "INSERT INTO  Tipo_Servicio (Descripcion) VALUES ('"+ ServicioTEXT.getText()+ "');" );
            } catch (SQLException ex) {
                Logger.getLogger(NuevoTS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Este servicio ya existe" ,"Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
            dispose();
    }//GEN-LAST:event_button1ActionPerformed

    private void EliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarbtnActionPerformed
        
        ResultSet rs = null;
            
        try {
            rs=BD.st.executeQuery("SELECT Descripcion FROM tipo_servicio ;");
        } catch (SQLException ex) {
            Logger.getLogger(NuevoTS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            rs.beforeFirst();
        } catch (SQLException ex) {
            Logger.getLogger(NuevoTS.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            while (rs.next())
            {
                if (ServicioTEXT.getText().equals(rs.getString("Descripcion"))){
                    System.out.println(rs.getString("Descripcion"));
                    System.out.println(ServicioTEXT.getText());
                    BD.st.execute(" DELETE FROM tipo_servicio  "
                               + " WHERE Descripcion='"+ServicioTEXT.getText()+ "' ;");
                    
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoTS.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        dispose ();
        
    }//GEN-LAST:event_EliminarbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoTS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NuevoTS().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoTS.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Eliminarbtn;
    private javax.swing.JTextField ServicioTEXT;
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
