/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Grafica;

import Objetos.manejador_bd;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Yanir
 */
public class NuevoProducto extends javax.swing.JFrame {

    /**
     * Creates new form NuevoCam
     */
    

    private static manejador_bd BD;
    private ResultSet rs = null;
    private boolean acept = true; 
    private int idproducto ;
    private  static ArrayList lista_servicios_asociados = new ArrayList(); 
    public NuevoProducto() throws SQLException {
        initComponents();
        this.setTitle("Crear un nuevo producto.");
        this.getContentPane().remove(Aceptar);
        java.util.Date date = new Date();
        BD = new manejador_bd();
        try {
            Fecha.setDate(date);
            date = new SimpleDateFormat("dd-MM-yyyy").parse("01-01-0001");
            Vencimiento_Date.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        activar_desactivar_duracion();
     
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        button1 = new java.awt.Button();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Producto = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        Costo = new javax.swing.JLabel();
        Kilometraje = new javax.swing.JLabel();
        Productotext = new javax.swing.JTextField();
        Marcatext = new javax.swing.JTextField();
        Costotext = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        CantidadSpinner = new javax.swing.JSpinner();
        ServicioLabel = new javax.swing.JLabel();
        SugeridoSpin = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DuracionSpinner = new javax.swing.JSpinner();
        FechaLb = new javax.swing.JLabel();
        Fecha = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        Vencimiento_Date = new com.toedter.calendar.JDateChooser();
        jRadioButton4 = new javax.swing.JRadioButton();
        Aceptar = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        AgregarServicio = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        DuracionCheckbox = new javax.swing.JCheckBox();

        jTextField1.setText("jTextField1");

        jTextField3.setText("jTextField3");

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Producto.setText("Producto");
        getContentPane().add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 51, -1, -1));

        Marca.setText("Marca");
        getContentPane().add(Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 89, -1, -1));

        Costo.setText("Costo");
        getContentPane().add(Costo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 127, -1, -1));

        Kilometraje.setText("Cantidad");
        getContentPane().add(Kilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 241, -1, -1));
        getContentPane().add(Productotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 48, 180, -1));
        Productotext.getAccessibleContext().setAccessibleName("Modelo");

        getContentPane().add(Marcatext, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 86, 180, -1));
        getContentPane().add(Costotext, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 124, 180, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Días");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 401, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Meses");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 401, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Km's");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 401, -1, -1));
        getContentPane().add(CantidadSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 238, 113, -1));

        ServicioLabel.setText("Servicios");
        getContentPane().add(ServicioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 451, -1, 23));
        getContentPane().add(SugeridoSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 276, 113, -1));

        jLabel2.setText("Sugerido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 279, -1, -1));

        jLabel3.setText("Duración");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 369, -1, -1));
        getContentPane().add(DuracionSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 363, 113, -1));

        FechaLb.setText("Fecha");
        getContentPane().add(FechaLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 165, -1, -1));
        getContentPane().add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 159, 113, -1));

        jLabel1.setText("Vencimiento");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 203, -1, -1));

        Vencimiento_Date.setMinSelectableDate(new java.util.Date(-62135749709000L));
        getContentPane().add(Vencimiento_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 197, 113, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Litros");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 401, -1, -1));

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 541, 82, -1));

        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 500, 82, -1));

        AgregarServicio.setText("Agregar servicio");
        AgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarServicioActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 451, -1, -1));

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 500, 82, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 541, 82, -1));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 500, 82, -1));

        DuracionCheckbox.setText("Insertar duración");
        DuracionCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DuracionCheckboxActionPerformed(evt);
            }
        });
        getContentPane().add(DuracionCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 322, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void AgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarServicioActionPerformed
      
        Serviciosasociados servi;
        try {
            servi = new Serviciosasociados();
            System.out.println("id : " + idproducto);
            
            if ((!Productotext.getText().equals("") && !Marcatext.getText().equals(""))  ){               
               lista_servicios_asociados  = servi.AgregarProducto(idproducto,Productotext.getText(), Marcatext.getText(), lista_servicios_asociados );
                servi.setVisible(true);
            }else{
                 JOptionPane.showMessageDialog(null, "Los campos 'Producto' y 'Marca' no pueden estar vacios. "  ,"Informacion", JOptionPane.WARNING_MESSAGE);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_AgregarServicioActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
       
        
            if (!Productotext.getText().equals("")){
                if (!Marcatext.getText().equals("")){
                   if (!Costotext.getText().equals("")){
                       if ((int) DuracionSpinner.getValue() >= 0){

                        if ((int) CantidadSpinner.getValue() >= 0){

                            Object producto [] = new Object [8];


                           producto [0]= Productotext.getText();
                           producto [1]= Marcatext.getText();
                           producto [2]= Integer.parseInt(Costotext.getText());
                           producto [3] = (int) CantidadSpinner.getValue();
                           producto [4] =DuracionSpinner.getValue().toString();
                           producto [5] =SugeridoSpin.getValue();
                           SimpleDateFormat formato = new SimpleDateFormat("YYYY-MM-dd");
                           producto [6] = formato.format(Fecha.getDate());
                           producto [7] = formato.format(Vencimiento_Date.getDate());
                           if (jRadioButton1.isSelected()){
                               producto [4] = producto [4] + " Dias";
                           }else{

                                if (jRadioButton2.isSelected()){
                                    producto [4] = producto [4] + " Meses";
                                }else{
                                        if (jRadioButton3.isSelected()){
                                            producto [4] = producto [4] + " Km";
                                        }else{
                                            if (jRadioButton4.isSelected()){
                                             producto [4] = producto [4] + " Litros";
                                        }
                                        }
                                }
                           }


                                System.out.println(Marcatext.getText());

                          if (acept){      
                            try {
                                BD.st.execute("SET SQL_SAFE_UPDATES = 0;" );
                                BD.st.execute("UPDATE  Inventario SET  Producto = '"+(String)producto[0]+"' ,Marca = '"+(String)producto[1]+"', Costo =  "+(int)producto[2]+" , "
                                        +" Cantidad = "+(int) producto[3]+" , Duracion = '"+(String)producto[4]+"' , Sugerido = '"+(int)producto[5]+"' , Fecha = '"+producto[6]+"', "
                                        +" Vencimiento = '"+producto[7]+"' "
                                        +" WHERE Producto = '"+(String)producto[0]+"' AND Marca = '"+(String)producto[1]+"' and Fecha = '"+producto[6]+"' ;" );
                            } catch (SQLException ex) {
                                Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            dispose();
                            
                          }else{
                              
                                try {
                                    rs=BD.st.executeQuery("SELECT *  FROM Inventario "
                                            + "WHERE Producto = '"+ Productotext.getText()+"' AND Marca = '"+Marcatext.getText() +"' ;");
                                    rs.beforeFirst();
                                    if(rs.next()){
                                        System.out.println("rs.getInt(\"Inventario_id\") : " + rs.getInt("id") );
                                        BD.st.execute("insert into historico_inventario (Inventario_id, Inventario_Producto, Inventario_Marca, Costo, Cantidad, Sugerido,Duracion, Fecha, Vencimiento) "
                                            + " values ( "+rs.getInt("id")+", '"+rs.getString("Producto")+"' , '"+rs.getString("Marca")+"' , "+rs.getFloat("Costo")+", "
                                            + " "+rs.getFloat("Cantidad")+", "+rs.getInt("Sugerido")+",'"+rs.getInt("Duracion")+"' , '"+rs.getDate("Fecha")+"', '"+rs.getDate("Vencimiento")+"' );" );
                              
                                    }
                                    
                                } catch (SQLException ex) {
                                    Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                
                                
                                
                                try {
                                BD.st.execute("SET SQL_SAFE_UPDATES = 0;" );
                                BD.st.execute("UPDATE  Inventario SET  Producto = '"+(String)producto[0]+"' ,Marca = '"+(String)producto[1]+"', Costo =  "+(int)producto[2]+" , "
                                        +" Cantidad = "+(int) producto[3]+" , Duracion = '"+(String)producto[4]+"' , Sugerido = '"+(int)producto[5]+"' , Fecha = '"+producto[6]+"', "
                                        +" Vencimiento = '"+producto[7]+"' "
                                        +" WHERE Producto = '"+(String)producto[0]+"' AND Marca = '"+(String)producto[1]+"' and Fecha = '"+producto[6]+"' ;" );
                            } catch (SQLException ex) {
                                Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                            }
                                
                          }
                            
                            try {
                                rs=BD.st.executeQuery("SELECT id  FROM Inventario "
                                        + "WHERE Producto = '"+ Productotext.getText()+"' AND Marca = '"+Marcatext.getText() +"' ;");
                                rs.beforeFirst();
                                asociar_producto_tipo_servicio(rs.getInt("id"));
                            } catch (SQLException ex) {
                                Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                            }
                          
                          
                            this.add(Editar);
                            this.add(Agregar);
                            this.getContentPane().remove(Aceptar);
                            repaint();
                            dispose();
                           }else{
                            JOptionPane.showMessageDialog(null, "La cantidad debe ser mayor a 0. " ,"Informacion", JOptionPane.WARNING_MESSAGE);
                        }   
                        }else{
                            JOptionPane.showMessageDialog(null, "La duración debe ser mayor a 0. " ,"Informacion", JOptionPane.WARNING_MESSAGE);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Debe ingresar un costo. " ,"Informacion", JOptionPane.WARNING_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "El campo 'Marca' no puede estar vacío. " ,"Informacion", JOptionPane.WARNING_MESSAGE);
                }
           }else{
               JOptionPane.showMessageDialog(null, "El campo 'Producto' no puede estar vacío. " ,"Informacion", JOptionPane.WARNING_MESSAGE);
           }
            
            
       
        
    }//GEN-LAST:event_AceptarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
       rellenar();
       acept = true;
       
    }//GEN-LAST:event_EditarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
  
        if (!Productotext.getText().equals("") && !Marcatext.getText().equals("") ){
            
            if(!lista_servicios_asociados.isEmpty()){
                int idinv = 0 ;
                String duracion = DuracionSpinner.getValue().toString();
                SimpleDateFormat formato = new SimpleDateFormat("YYYY/MM/dd");
                
                 if (jRadioButton1.isSelected()){
                              duracion.concat(" Días");
                           }else{

                                if (jRadioButton2.isSelected()){
                                    duracion.concat(" Meses");;
                                }else{
                                        if (jRadioButton3.isSelected()){
                                            duracion.concat(" Km");;
                                        }else{
                                            if (jRadioButton4.isSelected()){
                                             duracion.concat(" Litros");;
                                        }
                                        }
                                }
                           }
                

                try {
                    
                    if (DuracionCheckbox.isSelected()){
                        BD.st.execute("INSERT INTO `servi_cam`.`inventario` (`Producto`, `Marca`, `Costo`, "
                                + "`Cantidad`, `Duracion`, `Sugerido`, `Fecha`, `Vencimiento`) "
                                + "VALUES ('"+ Productotext.getText()+"', '"+ Marcatext.getText()+"', '"+ Costotext.getText()+"', "
                                + " '"+ CantidadSpinner.getValue()+"', '"+ duracion+"', '"+ SugeridoSpin.getValue()+"', "
                                + " '"+ formato.format(Fecha.getDate())+"', '"+ formato.format(Vencimiento_Date.getDate())+"');");
                    }else{
                        BD.st.execute("INSERT INTO `servi_cam`.`inventario` (`Producto`, `Marca`, `Costo`, "
                                + "`Cantidad`, `Sugerido`, `Fecha`, `Vencimiento`) "
                                + "VALUES ('"+ Productotext.getText()+"', '"+ Marcatext.getText()+"', '"+ Costotext.getText()+"', "
                                + " '"+ CantidadSpinner.getValue()+"', '"+ SugeridoSpin.getValue()+"', "
                                + " '"+ formato.format(Fecha.getDate())+"', '"+ formato.format(Vencimiento_Date.getDate())+"');");
                    }
                    
                    rs = BD.st.executeQuery("select last_insert_id() as id; ");

                    rs.beforeFirst();



                    if (rs.next()){
                        idinv = rs.getInt("id");
                    }
                    
                    asociar_producto_tipo_servicio(idinv);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                }


                
                JOptionPane.showMessageDialog(null, "El producto fue agregado BD.con exito. " ,"Informacion", JOptionPane.INFORMATION_MESSAGE);
                
            }else{
                JOptionPane.showMessageDialog(null, "Debe seleccionar al menos 1 servicio. " ,"Informacion", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Los campos 'Producto' y 'Marca' no pueden estar vacios. " ,"Informacion", JOptionPane.WARNING_MESSAGE);
        }
        
       acept = false;
    }//GEN-LAST:event_AgregarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try {
            BD.st.execute("DELETE FROM `servi_cam`.`inventario` WHERE `Producto`='"+Productotext.getText()+"' and`Marca`='"+Marcatext.getText()+"' ;");
        } catch (SQLException ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void DuracionCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DuracionCheckboxActionPerformed
      activar_desactivar_duracion ();
    }//GEN-LAST:event_DuracionCheckboxActionPerformed

    
    public void rellenar (){
        
          System.out.println("entre a rellenar.");
        
           if (!Productotext.getText().equals("")){
            if (!Marcatext.getText().equals("")){
              
       if ( Productotext.getText()!= null & Marcatext.getText()!= null ){
           
           System.out.println("entre a rellenar.");
           

            System.out.println(Productotext.getText());
            System.out.println(Marcatext.getText());

           try {
               rs=BD.st.executeQuery("SELECT *  FROM Inventario "
                       + "WHERE Producto = '"+ Productotext.getText()+"' AND Marca = '"+Marcatext.getText() +"' ;");
               
               
               rs.beforeFirst();
               

                      if (rs.next()){
                       
                                this.getContentPane().remove(Editar);
                                this.Aceptar.setBounds(this.Agregar.getBounds());
                                this.getContentPane().remove(Agregar);
                                this.add(Aceptar);
                                repaint();
                                idproducto = rs.getInt("id");
                                Costotext.setText(Integer.toString(rs.getInt("Costo")));
                                CantidadSpinner.setValue(rs.getInt("Cantidad"));
                                String palabra = rs.getString("Duracion");
                                Fecha.setDate(rs.getDate("Fecha"));
                                Vencimiento_Date.setDate(rs.getDate("Vencimiento"));
                                int posicion = palabra.indexOf(" ");
                                System.out.println(posicion);
                                DuracionSpinner.setValue(Integer.parseInt(palabra.substring(0 , posicion)));
                                System.out.println(palabra.substring(0 , posicion));
                                palabra = palabra.substring(posicion+1);
                                if (palabra.equals("Dias")){
                                    jRadioButton1.setSelected(true);
                                }else{
                                    if (palabra.equals("Meses")){
                                        jRadioButton2.setSelected(true);
                                    }else{
                                        if (palabra.equals("Km")){
                                            jRadioButton3.setSelected(true);
                                        }else {
                                            if (palabra.equals("Litros")){
                                            jRadioButton4.setSelected(true);
                                            }
                                        }
                                    }
                                }
                    
                                
                          
                            }
                            else{
                                    JOptionPane.showMessageDialog(null, "El producto no existe en el inventario. " ,"Informacion", JOptionPane.INFORMATION_MESSAGE);

               }
           } catch (SQLException ex) {
               Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
           }



       }

    }else{
    JOptionPane.showMessageDialog(null, "El campo 'Marca' no puede estar vacío. " ,"Informacion", JOptionPane.INFORMATION_MESSAGE);
    }
    }else{
    JOptionPane.showMessageDialog(null, "El campo 'Producto' no puede estar vacío. " ,"Informacion", JOptionPane.INFORMATION_MESSAGE);
    }
    }
    
    
    public void asociar_producto_tipo_servicio (int idinv){
        
        
                Iterator iterador_de_lista  = lista_servicios_asociados.iterator();
              
                
                if (idinv != 0){
                    while(iterador_de_lista.hasNext()){
                        try {
                            BD.st.execute("INSERT INTO inventario_has_tipo_servicio ( Inventario_id, Inventario_Producto, Inventario_Marca, Tipo_Servicio_idTipo_Servicio ) " +
                                          "SELECT "+idinv+" , '"+ Productotext.getText()+"' , '"+ Marcatext.getText()+"' ,  "+iterador_de_lista.next()+"  " +
                                          "FROM dual " +
                                          "WHERE NOT EXISTS (SELECT * FROM inventario_has_tipo_servicio " +
                                          "WHERE Inventario_id = "+idinv+" and Inventario_Producto = '"+ Productotext.getText()+"' and Inventario_Marca = '"+ Marcatext.getText()+"' )" );
                        } catch (SQLException ex) {
                            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                        }

                    }
                }else{
                     JOptionPane.showMessageDialog(null, "No se esta pasando un id de prodcuto correcto." ,"Informacion", JOptionPane.WARNING_MESSAGE);
                }
    }
    
    
    public void activar_desactivar_duracion (){
        if (DuracionCheckbox.isSelected()){
          DuracionSpinner.setEnabled(true);
          jRadioButton1.setEnabled(true);
          jRadioButton2.setEnabled(true);
          jRadioButton3.setEnabled(true);
          jRadioButton4.setEnabled(true);
        }else{
            DuracionSpinner.setEnabled(false);
            jRadioButton1.setEnabled(false);
            jRadioButton2.setEnabled(false);
            jRadioButton3.setEnabled(false);
            jRadioButton4.setEnabled(false);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());  
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(NuevoCam.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    new NuevoProducto().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Agregar;
    private javax.swing.JButton AgregarServicio;
    private javax.swing.JSpinner CantidadSpinner;
    private javax.swing.JLabel Costo;
    private javax.swing.JTextField Costotext;
    private javax.swing.JCheckBox DuracionCheckbox;
    private javax.swing.JSpinner DuracionSpinner;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JLabel FechaLb;
    private javax.swing.JLabel Kilometraje;
    private javax.swing.JLabel Marca;
    private javax.swing.JTextField Marcatext;
    private javax.swing.JLabel Producto;
    private javax.swing.JTextField Productotext;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel ServicioLabel;
    private javax.swing.JSpinner SugeridoSpin;
    private com.toedter.calendar.JDateChooser Vencimiento_Date;
    private java.awt.Button button1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
